### ISSUE TITLE
Remove the 'return' keywords

### ISSUE THREAD

**Issue by raphaelpor** [js-functional/js-funcional#2]
Hi guys!

What do you think of simplifying the arrow functions?
```diff
- let increment = () => {
-     return number += 1;
- }
+ let increment = () => number += 1;
```

**Comment by matheusml** [comment]
Yes, that's great advise. 
We could that, but unfortunately we'll need to change all of them.

**Comment by raphaelpor** [comment]
Do you accept a Pull Request for that? :smiley:

**Comment by matheusml** [comment]
Of course

**Comment by raphaelpor** [comment]
Done! :v:

**Comment by matheusml** [comment]
#3
