### ISSUE TITLE
Possible error in compose example

### ISSUE THREAD

**Issue by danillouz** [js-functional/js-funcional#8]
Hi, I stumbled on this repo while learning functional programming concepts. I'm still new to this, but I believe there is a `compose` call missing:

```
const reallyAngry = compose(exclaim, (toUpperCase, moreExclaim));
```

But shouldn't it be:
```
const reallyAngry = compose(exclaim, compose(toUpperCase, moreExclaim));
```

**Comment by matheusml** [comment]
You are totally right. We can confirm it here: http://www.es6fiddle.net/ijj7i31n/

Can you send us a pull request with the correction?

**Comment by danillouz** [comment]
Yes, will do!
